<a href="https://colab.research.google.com/github/shivajizirpe01-pixel/PDS-Assignment/blob/main/Practicleno4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Shivaji Zirpe

Class : SY- B

Roll no. : B-61

Batch - B4

                          PRACTICLE NO. : 4

  Aim : Numerical Computation with NumPy: Perform different computations using

Theory :

### 1. Explain the role of NumPy in the Python scientific computing ecosystem.

NumPy (Numerical Python) is the fundamental package for numerical computation in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It serves as the backbone for many other scientific computing libraries in Python, creating a powerful ecosystem for data analysis, machine learning, and scientific research. Its primary role includes:

*   **Foundation for numerical computing:** NumPy arrays are more efficient than Python lists for numerical operations, making it the de-facto standard for storing and manipulating numerical data.
*   **Interoperability:** Most scientific Python packages, such as SciPy, Matplotlib, Pandas, and Scikit-learn, are built upon NumPy arrays or interoperate seamlessly with them. This creates a unified and efficient environment for scientific computing.
*   **Mathematical operations:** It provides a vast collection of high-level mathematical functions to operate on these arrays, covering linear algebra, Fourier transforms, random number generation, and more.
*   **Performance:** By implementing operations in C and Fortran under the hood, NumPy achieves significant performance gains compared to native Python, especially for large datasets.

### 2. Why is NumPy considered faster than pure Python computations?

NumPy's speed advantage over pure Python computations stems from several key design choices and implementations:

*   **C Implementation:** The core of NumPy is written in C and Fortran, which are compiled languages. This allows operations to run much closer to the hardware, bypassing the Python interpreter's overhead.
*   **Contiguous Memory Allocation:** NumPy arrays store elements in a contiguous block of memory. This improves cache efficiency, as data can be accessed sequentially, which is much faster than accessing scattered data in Python lists (where elements can be stored anywhere in memory and are pointers to Python objects).
*   **Vectorization (Broadcasting):** NumPy allows you to perform operations on entire arrays at once, without explicit Python loops. This technique, called vectorization, leverages optimized C routines for these operations, avoiding the slow element-by-element iteration that Python loops entail.
*   **Homogeneous Data Types:** NumPy arrays are type-homogeneous, meaning all elements in an array must be of the same data type (e.g., all integers, all floats). This simplifies memory management and allows for more efficient storage and processing, as the interpreter doesn't need to check the type of each element during an operation.
*   **Optimized Algorithms:** NumPy uses highly optimized algorithms for common numerical tasks, often written by experts in numerical computing, which further contributes to its speed.

### 3. What types of mathematical operations can be performed using NumPy?

NumPy provides a comprehensive set of mathematical operations, ranging from basic arithmetic to advanced linear algebra and statistical functions. These include:

*   **Basic Arithmetic Operations:** Addition, subtraction, multiplication, division, modulo, exponentiation (element-wise).
    *   `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`
*   **Trigonometric Functions:** Sine, cosine, tangent, arcsine, arccosine, arctangent.
    *   `np.sin()`, `np.cos()`, `np.tan()`
*   **Logarithmic and Exponential Functions:** Natural logarithm, base-2 logarithm, base-10 logarithm, exponentiation.
    *   `np.log()`, `np.log2()`, `np.log10()`, `np.exp()`
*   **Statistical Operations:** Mean, median, standard deviation, variance, minimum, maximum, sum, product, percentiles.
    *   `np.mean()`, `np.median()`, `np.std()`, `np.var()`, `np.min()`, `np.max()`, `np.sum()`, `np.percentile()`
*   **Linear Algebra:** Dot product, matrix multiplication, inverse, determinant, eigenvalues, eigenvectors, solving linear equations.
    *   `np.dot()`, `np.matmul()`, `np.linalg.inv()`, `np.linalg.det()`, `np.linalg.eig()`
*   **Array Manipulation:** Reshaping, transposing, concatenating, splitting, stacking, broadcasting.
    *   `np.reshape()`, `np.transpose()`, `np.concatenate()`, `np.split()`, `np.stack()`
*   **Comparison and Logical Operations:** Element-wise comparisons (`>`, `<`, `>=`, `<=`, `==`, `!=`), logical AND, OR, NOT.
    *   `np.greater()`, `np.less()`, `np.equal()`, `np.logical_and()`, `np.logical_or()`
*   **Random Number Generation:** Generating random numbers from various distributions (uniform, normal, binomial, etc.).
    *   `np.random.rand()`, `np.random.randn()`, `np.random.randint()`

### 4. Explain indexing and slicing in NumPy arrays.

Indexing and slicing in NumPy arrays are powerful ways to access and modify specific elements or subarrays. They are similar to Python lists but offer more advanced capabilities for multidimensional arrays.

#### **Indexing**

Indexing refers to accessing individual elements. For a 1D array, it's similar to Python lists:

```python
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # Output: 10 (first element)
print(arr[-1])  # Output: 50 (last element)
```

For 2D (or higher-dimensional) arrays, you use a comma-separated tuple of indices, one for each dimension:

```python
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[0, 0]) # Output: 1 (row 0, column 0)
print(matrix[1, 2]) # Output: 6 (row 1, column 2)
print(matrix[2, 1]) # Output: 8 (row 2, column 1)
```

#### **Slicing**

Slicing allows you to extract subarrays (views) from an array. The syntax is `start:stop:step`, where `stop` is exclusive.

**1D Array Slicing:**

```python
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])     # Output: [20 30 40] (elements from index 1 up to (but not including) 4)
print(arr[:3])      # Output: [10 20 30] (elements from the beginning up to 3)
print(arr[3:])      # Output: [40 50 60] (elements from index 3 to the end)
print(arr[::2])     # Output: [10 30 50] (every second element)
print(arr[::-1])    # Output: [60 50 40 30 20 10] (reverse the array)
```

**2D Array Slicing:**

For 2D arrays, you can slice along each dimension:

```python
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0, :])     # Output: [1 2 3] (first row, all columns)
print(matrix[:, 1])     # Output: [2 5 8] (all rows, second column)
print(matrix[0:2, 1:3]) # Output:
                        # [[2 3]
                        #  [5 6]] (rows 0-1, columns 1-2)
print(matrix[::2, ::2]) # Output:
                        # [[1 3]
                        #  [7 9]] (every second row, every second column)
```

#### **Boolean (Mask) Indexing**

This is a powerful feature where you use a boolean array of the same shape as the original array to select elements. Elements corresponding to `True` in the boolean array are selected.

```python
arr = np.array([1, 5, 2, 8, 3, 9])
mask = (arr > 4)
print(mask)     # Output: [False  True False  True False  True]
print(arr[mask]) # Output: [5 8 9] (elements greater than 4)
```

#### **Fancy Indexing**

Fancy indexing involves passing an array of indices to select specific rows or columns in any order.

```python
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[[0, 2]]) # Output:
                      # [[1 2 3]
                      #  [7 8 9]] (select rows 0 and 2)
print(matrix[:, [0, 2]]) # Output:
                         # [[1 3]
                         #  [4 6]
                         #  [7 9]] (select columns 0 and 2)
```

### 5. How does NumPy integrate with libraries like:

NumPy's array object is the lingua franca of scientific Python, making it integrate seamlessly with many other libraries.

#### **a. Pandas**

Pandas is built on top of NumPy. Its primary data structures, `Series` (1D labeled array) and `DataFrame` (2D labeled table), internally use NumPy arrays to store data. This integration is crucial because:

*   **Efficiency:** Pandas leverages NumPy's optimized C-backed operations for high performance when handling large datasets, especially for numerical columns.
*   **Data Storage:** When you create a Pandas Series or DataFrame with numerical data, Pandas will often store that data in a NumPy array internally. For example, a DataFrame column containing only integers will be stored as a `dtype` of `int64` (a NumPy integer type).
*   **Interoperability:** You can easily convert between Pandas data structures and NumPy arrays:
    *   `df.values` or `series.values` returns the underlying NumPy array.
    *   `pd.DataFrame(numpy_array)` or `pd.Series(numpy_array)` creates Pandas objects from NumPy arrays.
*   **Missing Data (`NaN`):** Pandas uses NumPy's `np.nan` to represent missing (Not a Number) values in numerical columns, allowing for consistent handling of missing data.

Example:
```python
import pandas as pd
import numpy as np

s_np = np.array([1, 2, 3, 4, np.nan])
ps = pd.Series(s_np) # Pandas Series created from NumPy array
print(ps)

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
numpy_array_from_df = df.values # Get NumPy array from DataFrame
print(numpy_array_from_df)
```

#### **b. Matplotlib**

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It integrates extremely well with NumPy because:

*   **Plotting Data:** Matplotlib functions (like `plt.plot()`, `plt.scatter()`, `plt.hist()`) primarily accept NumPy arrays or array-like objects as input for coordinates, values, and other numerical data. This is its natural input format.
*   **Numerical Processing:** Before plotting, data often needs to be processed or generated numerically. NumPy provides the tools for these calculations (e.g., generating evenly spaced values with `np.linspace`, performing statistical aggregations, creating grids for contour plots).
*   **Efficiency:** By passing NumPy arrays directly to Matplotlib, the plotting library can efficiently handle and render large numerical datasets.

Example:
```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 2 * np.pi, 100) # Generate 100 points between 0 and 2*pi
y = np.sin(x) # Calculate sine of x using NumPy's vectorized function

plt.plot(x, y)
plt.title('Sine Wave')
plt.xlabel('Angle (radians)')
plt.ylabel('Sine Value')
plt.grid(True)
plt.show()
```

#### **c. Scikit-learn**

Scikit-learn is a powerful and widely used machine learning library in Python. Its integration with NumPy is fundamental:

*   **Input Data Format:** Scikit-learn models universally expect their input data (features `X` and target `y`) to be in the form of NumPy arrays (or Pandas DataFrames, which are internally based on NumPy arrays). This is the standard data format for training and prediction.
*   **Computational Foundation:** Many of the algorithms and utilities within Scikit-learn rely on NumPy for their underlying numerical operations, such as matrix multiplications, eigenvalue decompositions, and statistical calculations.
*   **Efficiency:** Given that machine learning often involves massive datasets and complex computations, Scikit-learn benefits immensely from NumPy's performance optimizations.
*   **Interchangeability:** Data preprocessing steps (scaling, normalization, etc.) often produce NumPy arrays, which can then be directly fed into Scikit-learn models.

Example:
```python
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np

# Generate some synthetic data using NumPy
X = np.random.rand(100, 1) * 10 # 100 samples, 1 feature
y = 2 * X + 1 + np.random.randn(100, 1) # y = 2x + 1 + noise

# Split data into training and testing sets (returns NumPy arrays)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train a linear regression model
model = LinearRegression()
model.fit(X_train, y_train) # Model expects NumPy arrays for training

# Make predictions on the test set
y_pred = model.predict(X_test) # Model expects NumPy arrays for prediction

print(f"Coefficients: {model.coef_[0][0]:.2f}")
print(f"Intercept: {model.intercept_[0]:.2f}")
```

In summary, NumPy provides the essential high-performance array computing capabilities that act as the numerical bedrock for these and many other scientific and data science libraries in the Python ecosystem.

In [ ]:
import numpy as np
import pandas as pd

# Load your dataset (make sure file name is correct)
df = pd.read_csv('/content/job_salary_prediction_dataset.csv')

print("Dataset Loaded Successfully!\n")
print(df.head())

# -------------------------------------------------
# 6. Matrix Addition and Multiplication
# -------------------------------------------------
print("\n--- Matrix Operations ---")

A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

print("Addition:\n", A + B)
print("Multiplication:\n", np.dot(A, B))

# -------------------------------------------------
# 7. Generate Random Numbers using NumPy
# -------------------------------------------------
print("\n--- Random Numbers ---")

print("Random floats:", np.random.rand(5))
print("Random integers:", np.random.randint(10, 50, size=5))

# -------------------------------------------------
# 8. Standard Deviation and Variance (from dataset)
# -------------------------------------------------
print("\n--- Statistics from Dataset ---")

# Select only numeric columns
numeric_df = df.select_dtypes(include=['int64', 'float64'])

if numeric_df.shape[1] == 0:
    print("No numeric columns found in dataset!")
else:
    print("Standard Deviation:\n", numeric_df.std())
    print("Variance:\n", numeric_df.var())

# -------------------------------------------------
# 9. NumPy Mathematical Functions
# -------------------------------------------------
print("\n--- NumPy Math Functions ---")

arr = np.array([1, 4, 9, 16, 25])

print("Square Root:", np.sqrt(arr))
print("Square:", np.square(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

# -------------------------------------------------
# 10. Python List vs NumPy Array
# -------------------------------------------------
print("\n--- List vs NumPy Array ---")

list1 = [1, 2, 3]
list2 = [4, 5, 6]

print("List Addition (join):", list1 + list2)

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Array Addition (element-wise):", array1 + array2)

# Speed comparison
import time

# List
start = time.time()
l = [i**2 for i in range(100000)]
list_time = time.time() - start

# NumPy
start = time.time()
a = np.arange(100000)**2
numpy_time = time.time() - start

print("List Time:", list_time)
print("NumPy Time:", numpy_time)

Dataset Loaded Successfully!

            job_title  experience_years education_level  skills_count  \
0         AI Engineer                10        Bachelor             2   
1        Data Analyst                 5        Bachelor            17   
2  Frontend Developer                18             PhD             4   
3    Business Analyst                19             PhD            13   
4     Product Manager                15        Bachelor             7   

        industry company_size   location remote_work  certifications  salary  
0     Healthcare       Medium      India      Hybrid               2  109413  
1        Telecom        Small  Australia          No               0   93764  
2          Media       Medium  Singapore          No               1  148123  
3         Retail       Medium     Canada         Yes               0  189123  
4  Manufacturing        Large     Sweden         Yes               0  165069  

--- Matrix Operations ---
Matrix A:
 [[2 4]
 [6 8]]
Matr

## Conclusion

This practical demonstration has highlighted the fundamental aspects and immense power of NumPy in numerical computation within Python. We've explored its core features, including:

*   **Efficient Array Creation and Manipulation:** From lists to multidimensional arrays, NumPy provides intuitive ways to create and reshape data structures.
*   **Vectorized Operations:** Performing element-wise arithmetic, mathematical functions, and statistical calculations across entire arrays dramatically simplifies code and boosts performance compared to traditional Python loops.
*   **Advanced Indexing and Slicing:** Powerful methods for accessing and modifying array elements, including basic indexing, slicing, boolean masking, and fancy indexing.
*   **Linear Algebra Capabilities:** Solving systems of equations and performing matrix operations effortlessly.
*   **Broadcasting:** A flexible mechanism for working with arrays of different shapes.
*   **Performance Benefits:** Through direct comparisons, we observed the significant speed advantages of NumPy operations over pure Python, especially for large datasets, due to its C-optimized backend.
*   **Ecosystem Integration:** Understanding how NumPy serves as the bedrock for other critical libraries like Pandas, Matplotlib, and Scikit-learn, enabling a cohesive and high-performance scientific computing environment.

In essence, NumPy is an indispensable tool for anyone working with numerical data in Python, providing the efficiency, flexibility, and mathematical functionalities required for tasks ranging from data analysis and scientific research to machine learning and deep learning. Mastering NumPy is a crucial step towards effective and high-performance computing in Python.